### ISSUE TITLE
Port in logic from Item Positioner script

### ISSUE THREAD

**Issue by SteveTownsend** [SteveTownsend/AllGUDMeshGen#10]
Not supported currently. idk what this even does

**Comment by shoegorath** [comment]
IIRC it positions hot keyed potions and even items like azura star and gold pouches on yourself

**Comment by SteveTownsend** [comment]
thanks, I did some digging and it does not look like this one will be too
hard to implement

**Comment by SteveTownsend** [comment]
Can do this now UI is ready

**Comment by SteveTownsend** [comment]
Released in v1.12.0
