### ISSUE TITLE
blocking error

### ISSUE THREAD

**Issue by svieirn** [SteveTownsend/AllGUDMeshGen#41]
i'm trying to run the patcher but i get this error
MeshHandler.cs(293,54): error CS7036: There is no argument given that corresponds to the required formal parameter 'destination' of 'MemoryExtensions.ToLower(ReadOnlySpan<char>, Span<char>, CultureInfo?)'

**Comment by SteveTownsend** [comment]
Sounds like it';s trying to run on the wrong version of .Net. Can you
revert to 'last settings' or 'preferred settings'  in the config for the
patcher? Sorry, my mod setup is down rn due to HDD failure. You could try
Synthesis Discord if you cannot get it going.
